POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmNvcyBDb25ncmVnYWRvIiwiaWQiOiI2NjNiNjFlOTk5NzcxNTRjZjBmYTA5NGYiLCJpYXQiOjE3MTUyNTkzNjEsImV4cCI6MTcxNTI2Mjk2MX0.dYvLwXSYbJB_ylbk66UsUxCl1FzMGmyZeZtasAJAHpY

{
    //"username": "Marcos Congregado",
    //"name": "Lobo",
    //"password": "loboNegro"
    "author": "Marcos Congre", 
    "title": "El amanecer en el mas alla",
    "URL": "REYnando.com" 
} 

